[project]
name = "bluerecording"
dynamic = ["version"]
description = "A tool for calculating extracellular recording lead fields"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "morphio",
    "bluepysnap",
    "voxcell",
    "scikit-learn"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-forked",
    "pytest-mpi"
]
notebooks = [
    "jupyterlab",
    "ipympl"
]
all = [
    "bluerecording[test]",
    "bluerecording[notebooks]"
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
local_scheme = "no-local-version"

[tool.hatch.build.targets.sdist]
only-include = ["bluerecording"]

[tool.hatch.build.targets.wheel]
packages = ["bluerecording"]

[project.scripts]
bluerecording = "bluerecording.cli:main"
