[tox]
envlist = lint-fix, format-fix

[testenv:lint]
deps = ruff
skip_install = true
commands =
    ruff check .

[testenv:lint-fix]
deps = ruff
skip_install = true
commands =
    ruff check --fix .

[testenv:format]
deps = ruff
skip_install = true
commands =
    ruff format --check .

[testenv:format-fix]
deps = ruff
skip_install = true
commands =
    ruff format .
